/*
 * File: app/view/resourceManager/PhotographUpload.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BqeApp.view.resourceManager.PhotographUpload', {
    extend: 'Ext.form.Panel',
    alias: 'widget.photographupload',

    requires: [
        'Ext.field.TextArea'
    ],

    config: {
        id: 'photographUpload',
        items: [
            {
                xtype: 'textfield',
                itemId: 'photographUploadDate',
                label: '日期:',
                name: 'photographUploadDate'
            },
            {
                xtype: 'textfield',
                itemId: 'photographUploadPerson',
                label: '上传者:',
                name: 'photographUploadPerson'
            },
            {
                xtype: 'textfield',
                itemId: 'photographUploadCustomer',
                label: '客户:',
                name: 'photographUploadCustomer'
            },
            {
                xtype: 'textfield',
                itemId: 'photographUploadLocation',
                label: '位置:',
                name: 'photographUploadLocation'
            },
            {
                xtype: 'textfield',
                itemId: 'photographUploadPhoto',
                label: '拍照:',
                name: 'photographUploadPhoto'
            },
            {
                xtype: 'textareafield',
                itemId: 'photographUploadContent',
                label: '描述:',
                name: 'photographUploadContent'
            }
        ]
    }

});