/*
 * File: app/view/resourceManager/BusinessopportunityUpload.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BqeApp.view.resourceManager.BusinessopportunityUpload', {
    extend: 'Ext.form.Panel',
    alias: 'widget.businessopportunityupload',

    requires: [
        'Ext.field.TextArea'
    ],

    config: {
        id: 'businessopportunityUpload',
        items: [
            {
                xtype: 'textfield',
                itemId: 'businessopportunityUploadDate',
                label: '日期:',
                name: 'businessopportunityUploadDate'
            },
            {
                xtype: 'textfield',
                itemId: 'businessopportunityUploadPerson',
                label: '上传者:',
                name: 'businessopportunityUploadPerson'
            },
            {
                xtype: 'textfield',
                itemId: 'businessopportunityUploadCustomer',
                label: '客户:',
                name: 'businessopportunityUploadCustomer'
            },
            {
                xtype: 'textareafield',
                itemId: 'businessopportunityUploadDescribe',
                label: '商机描述:',
                name: 'businessopportunityUploadDescribe'
            }
        ]
    }

});