/*
 * File: app/controller/main/AssistantNavigationController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BqeApp.controller.main.AssistantNavigationController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            assistantNavigation: '#assistantNavigation',
            attendanceTypeList: 'pushcardtype #attendanceTypeList',
            workReport: '#workReport',
            imgSetting: 'assistantnavigation #imgSetting',
            businessopportunityUpload: '#businessopportunityUpload',
            photographUpload: '#photographUpload',
            commitApply: '#commitApply',
            customerDetailsPanel: '#customerDetailsPanel'
        },

        control: {
            "assistantNavigation": {
                push: 'onNavigationviewPush',
                pop: 'onNavigationviewPop'
            },
            "assistantnavigation list": {
                itemsingletap: 'onListItemSingletap'
            },
            "imgSetting": {
                tap: 'onSystemSettingTap'
            },
            "#fastOperationMain": {
                itemsingletap: 'onFastOperationMainItemSingletap'
            },
            "slidingmenu button": {
                tap: 'onSlideMenuButtonTap'
            },
            "#bqeAssistantMainPanel": {
                initialize: 'onBqeAssistantMainPanelInitialize'
            }
        }
    },

    /*
        NavigationView执行push操作时的方法

    */
    onNavigationviewPush: function(navigationview, view, eOpts) {
        // console.log('入栈'+view.getId()+'->>itemId:'+view.getItemId());

        var me = this;
        if(me.getWorkReport()==view||me.getBusinessopportunityUpload()==view||me.getPhotographUpload()==view||me.getCommitApply()==view)
        {
            var button = Ext.create('Ext.Button',{
                text:'提交',
                align: 'right',
                itemId:'submit'
            });
            navigationview.getNavigationBar().add(button);
        }
    },

    /*
         NavigationView执行pop操作时的方法

    */
    onNavigationviewPop: function(navigationview, view, eOpts) {
        // console.log('出栈'+view.getId()+'->>itemId:'+view.getItemId());

        if(navigationview.getActiveItem()==navigationview.getAt(0)){
            var nav = navigationview;
            var title = nav.getAt(0).getActiveItem().title;
            nav.getNavigationBar().setTitle(title);
        }
    },

    /*

        所有List的单击跳转事件
    */
    onListItemSingletap: function(dataview, index, target, record, e, eOpts) {
        var me = this;
        if(dataview.getId()==='customerManageList'){
            me.switchView('customerdetailspanel','联系人详情');
            me.getCustomerDetailsPanel().setValues({
                customerMobile:record.get('customer_mobile'),	//手机
                customerTelephone:record.get('customer_telephone'),	//座机
                customerAddress:record.get('customer_address'),	//地址
                customerMallAccount:'',
                customerQQ:'',	//QQ
                customerWX:'',	//微信
                customerEmail:''	//邮箱
            });
            return;
        }
        me.dataItemSingleTap(record);
    },

    onSystemSettingTap: function(button, e, eOpts) {
        var me = this;
        // me.switchView('loginpanel','登录界面');
        me.switchView('systemsettinglist','系统设置');
    },

    /*
        快捷功能跳转事件

    */
    onFastOperationMainItemSingletap: function(dataview, index, target, record, e, eOpts) {
        this.dataItemSingleTap(record);

    },

    onSlideMenuButtonTap: function(button, e, eOpts) {

        var me = this;
        switch(button.getItemId()){
            case  'btnAccountSecurity':
                me.switchView('loginpanel','登录界面');
                break;
            case  'btnFeedBack':
                alert('意见反馈');
                break;
            case  'btnAboutUs':
                alert('关于我们');
                break;
            case  'btnDropOut':
                alert('退出登陆');
                break;
        }
        Ext.Viewport.removeMenu('left');
    },

    onBqeAssistantMainPanelInitialize: function(component, eOpts) {
        document.addEventListener("deviceready", onDeviceReady, false);
    },

    dataItemSingleTap: function(record) {
        var me = this;
        var xtype = record.get('xtype');
        var title = record.get('title');

        if(xtype){
            me.switchView(xtype,title);
        }else{
            alert('暂无此功能');
        }
    },

    /*
        主要跳转方法

    */
    switchView: function(xtype, title) {
        this.getAssistantNavigation().push({
            xtype:xtype,
            title:title
        });
    },

    onDeviceReady: function() {
        // checkConnection();
        document.addEventListener("backbutton", eventBackButton, false); //返回键
        document.addEventListener("menubutton", eventMenuButton, false); //菜单键
        document.addEventListener("searchbutton", eventSearchButton, false); //搜索键
    },

    onConfirm: function(androidButton) {
        if (androidButton == '1') {
            navigator.app.exitApp();
        } else {

        }
    },

    eventBackButton: function() {
        navigator.notification.confirm('点错按钮了？', // 显示信息
                                       onConfirm, // 按下按钮后触发的回调函数，返回按下按钮的索引
                                       '退出应用', // 标题
                                       '确定,取消' // 按钮标签
                                      );
    }

});