/*
 * File: app/store/PushCardTypeStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BqeApp.store.PushCardTypeStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        data: [
            {
                xtype: 'pushcarddetail',
                title: '签到',
                state: 0
            },
            {
                xtype: 'pushcarddetail',
                title: '签退',
                state: 0
            }
        ],
        storeId: 'PushCardTypeStore',
        fields: [
            {
                name: 'xtype'
            },
            {
                name: 'title'
            },
            {
                name: 'state'
            }
        ]
    }
});