/*
 * File: app/view/dailyOffice/attendance/query/AttendanceQueryView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BqeApp.view.dailyOffice.attendance.query.AttendanceQueryView', {
    extend: 'Ext.form.Panel',
    alias: 'widget.attendancequeryview',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Text',
        'Ext.Button',
        'Ext.Spacer'
    ],

    config: {
        id: 'attendanceQueryView',
        items: [
            {
                xtype: 'fieldset',
                itemId: 'timeFieldSet',
                items: [
                    {
                        xtype: 'textfield',
                        itemId: 'startTime',
                        label: '起始时间:',
                        name: 'startTime'
                    },
                    {
                        xtype: 'textfield',
                        itemId: 'endTime',
                        label: '终止时间:',
                        name: 'endTime'
                    },
                    {
                        xtype: 'container',
                        padding: '6 0 6 0',
                        layout: {
                            type: 'hbox',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'btnConfirmTime',
                                text: '确定'
                            },
                            {
                                xtype: 'spacer',
                                width: 80
                            },
                            {
                                xtype: 'button',
                                itemId: 'btnResetTime',
                                text: '重置'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});