/*
 * File: app/view/commercialManager/customer/CustomerDetailsPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BqeApp.view.commercialManager.customer.CustomerDetailsPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.customerdetailspanel',

    requires: [
        'Ext.Img',
        'Ext.Label',
        'Ext.form.FieldSet',
        'Ext.field.Text',
        'Ext.Button',
        'Ext.Spacer'
    ],

    config: {
        id: 'customerDetailsPanel',
        scrollable: 'vertical',
        items: [
            {
                xtype: 'container',
                itemId: 'customerInfoContainer',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'image',
                        height: 80,
                        itemId: 'customerPhoto',
                        margin: 10,
                        width: 80,
                        src: 'resources/img/icon_customer_namage.svg'
                    },
                    {
                        xtype: 'label',
                        centered: true,
                        html: '账号名称',
                        itemId: 'customerName'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: '电话',
                items: [
                    {
                        xtype: 'textfield',
                        disabled: true,
                        itemId: 'customerMobile',
                        label: '手机:',
                        name: 'customerMobile'
                    },
                    {
                        xtype: 'textfield',
                        disabled: true,
                        itemId: 'customerTelephone',
                        label: '座机:',
                        name: 'customerTelephone'
                    },
                    {
                        xtype: 'container',
                        padding: '6 0 6 0',
                        layout: {
                            type: 'hbox',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'BtnCustomerDetailsPanelCall',
                                ui: 'plain',
                                iconCls: 'icon_telephone',
                                text: '呼叫'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                itemId: 'BtnCustomerDetailsPanelMessage',
                                ui: 'plain',
                                iconCls: 'icon_message',
                                text: '信息'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                itemId: 'BtnCustomerDetailsPanelEdit',
                                ui: 'plain',
                                iconCls: 'icon_edit',
                                text: '编辑'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: '地址',
                items: [
                    {
                        xtype: 'textfield',
                        disabled: true,
                        itemId: 'customerAddress',
                        label: '',
                        name: 'customerAddress'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: '其他',
                items: [
                    {
                        xtype: 'textfield',
                        disabled: false,
                        itemId: 'customerMallAccount',
                        label: '商城账号:',
                        name: 'customerMallAccount'
                    },
                    {
                        xtype: 'textfield',
                        disabled: true,
                        itemId: 'customerQQ',
                        label: 'QQ:',
                        name: 'customerQQ'
                    },
                    {
                        xtype: 'textfield',
                        disabled: true,
                        itemId: 'customerWX',
                        label: '微信:',
                        name: 'customerWX'
                    },
                    {
                        xtype: 'textfield',
                        disabled: true,
                        itemId: 'customerEmail',
                        label: '邮箱:',
                        name: 'customerEmail'
                    }
                ]
            },
            {
                xtype: 'button',
                itemId: 'BtnAddMore',
                margin: '10 80 80 80',
                width: 150,
                iconCls: 'add',
                text: '添加更多'
            }
        ]
    }

});