/*
 * File: app/view/main/HomeTabPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BqeApp.view.main.HomeTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.hometabpanel',

    requires: [
        'BqeApp.view.fastOperate.FastOperationMain',
        'BqeApp.view.dailyOffice.DailyOfficeMain',
        'BqeApp.view.commercialManager.CommercialManageMain',
        'BqeApp.view.resourceManager.ResourceManageMain',
        'Ext.tab.Bar',
        'Ext.dataview.List'
    ],

    config: {
        title: '快捷功能',
        id: 'homeTabPanel',
        tabBar: {
            border: 0,
            docked: 'bottom',
            layout: {
                type: 'hbox',
                pack: 'justify'
            }
        },
        items: [
            {
                xtype: 'fastoperationmain',
                title: '快捷功能',
                iconCls: 'icon-fastoperation'
            },
            {
                xtype: 'dailyofficemain',
                title: '日常办公',
                iconCls: 'icon-dailyoffice'
            },
            {
                xtype: 'commercialmanagemain',
                title: '商务管理',
                iconCls: 'icon-commercialmanage'
            },
            {
                xtype: 'resourcemanagemain',
                title: '资源管理',
                iconCls: 'icon-resourcemanage'
            }
        ]
    }

});