/*
 * File: app/view/main/LoginPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BqeApp.view.main.LoginPanel', {
    extend: 'Ext.Container',
    alias: 'widget.loginpanel',

    requires: [
        'Ext.Img',
        'Ext.form.FieldSet',
        'Ext.field.Password',
        'Ext.Button',
        'Ext.Label'
    ],

    config: {
        height: '100%',
        id: 'loginPanel',
        layout: 'vbox',
        items: [
            {
                xtype: 'image',
                height: 110,
                itemId: 'loginLogo',
                margin: '5 auto',
                width: 'auto',
                src: 'resources/img/logo.png'
            },
            {
                xtype: 'container',
                id: 'loginForm',
                margin: '0 20 0 20',
                items: [
                    {
                        xtype: 'fieldset',
                        id: 'loginFieldset',
                        margin: '-2 0 16 0',
                        title: '',
                        items: [
                            {
                                xtype: 'textfield',
                                itemId: 'loginAccount',
                                label: '账号:',
                                name: 'loginAccount'
                            },
                            {
                                xtype: 'passwordfield',
                                itemId: 'loginPassword',
                                label: '密码:',
                                name: 'loginPassword'
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        itemId: 'loginBtnLogin',
                        margin: '',
                        ui: 'action',
                        text: '登录'
                    },
                    {
                        xtype: 'container',
                        id: 'loginFormLabel',
                        margin: '10 0 0 0',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'label',
                                html: '新用户',
                                id: 'loginNewUser'
                            },
                            {
                                xtype: 'label',
                                docked: 'right',
                                html: '忘记密码',
                                id: 'loginForgetPassword'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});