/*
 * File: app/view/main/SlidingMenu.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BqeApp.view.main.SlidingMenu', {
    extend: 'Ext.Menu',
    alias: 'widget.slidingmenu',

    requires: [
        'Ext.Container',
        'Ext.Img',
        'Ext.Label',
        'Ext.Button'
    ],

    config: {
        cls: 'slidemaincls',
        items: [
            {
                xtype: 'container',
                cls: 'slidecls',
                itemId: 'userInfo',
                items: [
                    {
                        xtype: 'image',
                        height: 64,
                        itemId: 'userImg',
                        width: '',
                        src: 'resources/img/icon_about_us.svg'
                    },
                    {
                        xtype: 'label',
                        html: '美食官',
                        itemId: 'userName'
                    }
                ]
            },
            {
                xtype: 'button',
                cls: 'btnslide',
                itemId: 'btnAccountSecurity',
                margin: 20,
                ui: 'plain',
                iconCls: 'icon_account_number',
                text: '账号安全'
            },
            {
                xtype: 'button',
                cls: 'btnslide',
                itemId: 'btnFeedBack',
                margin: 20,
                ui: 'plain',
                iconCls: 'icon_feedback',
                text: '意见反馈'
            },
            {
                xtype: 'button',
                cls: 'btnslide',
                itemId: 'btnAboutUs',
                margin: 20,
                ui: 'plain',
                iconCls: 'icon_about_us',
                text: '关于我们'
            },
            {
                xtype: 'button',
                cls: 'btnslide',
                itemId: 'btnDropOut',
                margin: 20,
                ui: 'plain',
                iconCls: 'icon_drop_out',
                text: '退出登陆'
            }
        ]
    }

});