/*
 * File: app/controller/dailyOffice/WorkReportController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BqeApp.controller.dailyOffice.WorkReportController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            workReport: '#workReport',
            workReportCheckPerson: '#workReportCheckPerson',
            workReportTitle: '#workReportTitle',
            workReportType: '#workReportType',
            workReportNeedCheck: '#workReportNeedCheck',
            workReportContent: '#workReportContent',
            submit: '#assistantNavBar #submit'
        },

        control: {
            "workreport": {
                initialize: 'onWorkReportInitialize'
            },
            "panel #workReport": {
                deactivate: 'onWorkReportDeactivate'
            },
            "submit": {
                tap: 'onSubmitTap'
            }
        }
    },

    onWorkReportInitialize: function(component, eOpts) {
        console.log('初始化工作上报');



        var WorkReportJsonPStore=Ext.getStore('workReportJsonPStore');

        WorkReportJsonPStore.load({
            callback: function(records, operation, success) {
                console.log(records);
                this.getWorkReport().setValues({
                    workReportTitle:records[0].get('workReportCheckPerson')
                });
            },
            scope: this
        });



    },

    onWorkReportDeactivate: function(oldActiveItem, container, newActiveItem, eOpts) {
        var me = this;

        if(me.getSubmit()){
            console.log('销毁按钮');
            me.getSubmit().destroy();
        }
    },

    onSubmitTap: function(button, e, eOpts) {
        console.log('确认上报');

        var form=this.getWorkReport();
        var WorkReportJsonPStore=Ext.getStore('workReportJsonPStore');
        var values = form.getValues();

        //把对象转成JSON格式的字符串
        console.log(Ext.JSON.encode(values)+'values');

        Ext.data.JsonP.request({
            url: 'http://192.168.0.100/appserver/server.php/work/workReports/store',
            params:values,
            success: function(result) {
                console.log(Ext.JSON.encode(result)+'成功');
            },
            failure: function(result) {
                alert('失败'+result);
            }
        });


    },

    getNowFormatDate: function() {
        var day = new Date();

        var Year = 0;
        var Month = 0;
        var Day = 0;
        var CurrentDate = "";
        //初始化时间
        //Year       = day.getYear();//有火狐下2008年显示108的bug
        Year       = day.getFullYear();//ie火狐下都可以
        Month      = day.getMonth()+1;
        Day        = day.getDate();

        CurrentDate += Year + "-";

        if (Month >= 10 )
        {
            CurrentDate += Month + "-";
        }
        else
        {
            CurrentDate += "0" + Month + "-";
        }
        if (Day >= 10 )
        {
            CurrentDate += Day ;
        }
        else
        {
            CurrentDate += "0" + Day ;
        }

        return CurrentDate;
    }

});