/*
 * File: app/view/dailyOffice/attendance/pushcard/PushCardDetail.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BqeApp.view.dailyOffice.attendance.pushcard.PushCardDetail', {
    extend: 'Ext.Container',
    alias: 'widget.pushcarddetail',

    requires: [
        'Ext.Button',
        'Ext.Container',
        'Ext.Label',
        'Ext.Img',
        'Ext.field.TextArea'
    ],

    config: {
        id: 'pushCardDetail',
        items: [
            {
                xtype: 'button',
                itemId: 'obtainPositionBtn',
                iconCls: 'locate',
                text: '定位中...'
            },
            {
                xtype: 'container',
                itemId: 'photoContainer',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'label',
                        html: '现场照片',
                        width: '25%'
                    },
                    {
                        xtype: 'container',
                        width: '75%',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'image',
                                height: 65,
                                width: 65,
                                src: 'resources/img/logo.png'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'textareafield',
                itemId: 'signDescription',
                label: '签到说明',
                labelWidth: '31%',
                placeHolder: '在此输入签到说明'
            }
        ]
    }

});