/*
 * File: app/controller/dailyOffice/ApplyMangerController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BqeApp.controller.dailyOffice.ApplyMangerController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            submit: '#assistantNavBar #submit'
        },

        control: {
            "assistantnavigation #commitApply": {
                deactivate: 'onCommitApplyDeactivate'
            }
        }
    },

    onCommitApplyDeactivate: function(oldActiveItem, container, newActiveItem, eOpts) {
        var me = this;

        if(me.getSubmit()){
            me.getSubmit().destroy();
        }
    }

});