/*
 * File: app/controller/fastOperate/FastOperationMainController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BqeApp.controller.fastOperate.FastOperationMainController', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "#fastOperationMain": {
                initialize: 'onFastOperationMainInitialize'
            },
            "togglefield": {
                initialize: 'onTogglefieldInitialize',
                change: 'onTogglefieldChange'
            }
        }
    },

    onFastOperationMainInitialize: function(component, eOpts) {
        var fastOperationStore = Ext.getStore('fastOperationStore');
        fastOperationStore.load();

        //如果没有“添加按钮”,则向Store添加“添加按钮”
        if(!fastOperationStore.findRecord('functionId','addFunction')){
            fastOperationStore.add({
                functionId: 'addFunction',
                xtype: 'fastoperationsetting',
                iconPath: 'resources/img/icon_addition.svg',
                title: '添加功能',
                moreIcon:false
            });
            fastOperationStore.sync();
        }
    },

    /*
        设置快捷功能 界面初始化

    */
    onTogglefieldInitialize: function(component, eOpts) {
        var fastOperationStore = Ext.getStore('fastOperationStore');
        var record = fastOperationStore.findRecord('functionId',component.getItemId());

        if(record){
           component.setValue(1);
        }
    },

    onTogglefieldChange: function(togglefield, newValue, oldValue, eOpts) {
        var fastOperationStore = Ext.getStore('fastOperationStore');

        if(newValue===1 && oldValue===0){

            // 如果localStorage已有该记录
            if(fastOperationStore.findRecord('functionId',togglefield.getItemId())){
                return;
            }

            var storeId = null;
            console.log('添加');
            switch(togglefield.type){
                case 'dailyOffice':
                    storeId = 'dailyOfficeStore';
                    break;
                case 'commercialManager':
                    storeId = 'commercialManagementStore';
                    break;
                case 'resourceManager':
                    storeId = 'resourcesManagementStore';
                    break;
                case 'applyManage':
                    storeId = 'applyManageStore';
                    break;
                case 'attendanceManage':
                    storeId = 'attendanceManageStore';
                    break;
                case 'priceManage':
                    storeId = 'priceManageStore';
                    break;
                default:
                    alert('类型错误');
                    console.log('类型错误');
                    break;
            }

            var fromStore = Ext.getStore(storeId);
            var record = fromStore.findRecord('functionId',togglefield.getItemId());

            if(!record){
                alert('不存在');
                console.log('不存在');
                return;
            }

            record.phantom = true; //表示record是新增的
            fastOperationStore.add(record);
        }

        if(newValue===0 && oldValue===1){
            console.log('删除');
            fastOperationStore.remove(fastOperationStore.findRecord('functionId',togglefield.getItemId()));
        }

        fastOperationStore.sync();
    }

});