/*
 * File: app/view/dailyOffice/WorkReport.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    工作上报
*/
Ext.define('BqeApp.view.dailyOffice.WorkReport', {
    extend: 'Ext.form.Panel',
    alias: 'widget.workreport',

    alternateClassName: [
        'WorkReport'
    ],
    requires: [
        'Ext.Container',
        'Ext.Label',
        'Ext.field.Radio',
        'Ext.field.TextArea'
    ],

    config: {
        id: 'workReport',
        items: [
            {
                xtype: 'textfield',
                id: 'workReportTitle',
                label: '标题:',
                name: 'workReportTitle'
            },
            {
                xtype: 'textfield',
                id: 'workReportType',
                label: '上报类型:',
                name: 'workReportType'
            },
            {
                xtype: 'container',
                id: 'workReportContainer',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'label',
                        cls: 'workreportlabel',
                        html: '申请审核:',
                        id: 'workReportIsCheck'
                    },
                    {
                        xtype: 'radiofield',
                        itemId: 'workReportYesCheck',
                        label: '是',
                        labelAlign: 'right',
                        name: 'workReportNeedCheck',
                        value: '1'
                    },
                    {
                        xtype: 'radiofield',
                        itemId: 'workReportNoCheck',
                        label: '否',
                        labelAlign: 'right',
                        name: 'workReportNeedCheck',
                        value: '0'
                    }
                ]
            },
            {
                xtype: 'textfield',
                id: 'workReportCheckPerson',
                label: '审核人:',
                name: 'workReportCheckPerson'
            },
            {
                xtype: 'textareafield',
                id: 'workReportContent',
                label: '内容:',
                name: 'workReportContent'
            }
        ]
    }

});