/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({

    requires: [
        'Ext.data.JsonP'
    ],
    viewport: {
        xclass: 'Ext.viewport.Viewport'
    },

    models: [
        'CategoriesModel',
        'ArticleListModel',
        'LoginModel',
        'CustomerInfoModel',
        'WorkReportModel',
        'AttendanceQueryModel',
        'FunctionListModel'
    ],
    stores: [
        'ArticleListStore',
        'LoginStore',
        'CustomerContactJsonPStore',
        'WorkReportJsonPStore',
        'attendanceQueryJsonPStore',
        'functionListStore.DailyOfficeStore',
        'functionListStore.CommercialManagementStore',
        'functionListStore.ResourcesManagementStore',
        'PushCardTypeStore',
        'ReportQueryJsonPStore',
        'functionListStore.FastOperationStore',
        'functionListStore.SystemSettingsStore',
        'functionListStore.AttendanceManageStore',
        'functionListStore.ApplyManageStore',
        'functionListStore.PriceManageStore'
    ],
    views: [
        'main.LoginPanel',
        'main.AssistantNavigation',
        'dailyOffice.attendance.query.AttendanceQueryView',
        'main.HomeTabPanel',
        'main.BqeAssistantMainPanel',
        'dailyOffice.attendance.AttendanceManage',
        'dailyOffice.attendance.pushcard.PushCardType',
        'dailyOffice.attendance.pushcard.PushCardDetail',
        'commercialManager.customer.CustomerDetailsPanel',
        'dailyOffice.WorkReport',
        'commercialManager.customer.CustomerManageList',
        'dailyOffice.DailyOfficeMain',
        'dailyOffice.attendance.query.AttendanceQueryDetail',
        'fastOperate.FastOperationMain',
        'main.SlidingMenu',
        'fastOperate.FastOperationSetting',
        'main.SystemSettingList',
        'dailyOffice.applyManage.CommitApply',
        'dailyOffice.applyManage.ApplyQuery',
        'dailyOffice.applyManage.ApplyManageMain',
        'commercialManager.priceManage.PriceManageMian',
        'resourceManager.PhotographUpload',
        'resourceManager.BusinessopportunityUpload',
        'dailyOffice.announcement.AnnouncementQuery'
    ],
    controllers: [
        'main.AssistantNavigationController',
        'dailyOffice.WorkReportController',
        'dailyOffice.AttendanceManageController',
        'main.BqeAssistantMainController',
        'commercialManage.CommercialManagerController',
        'dailyOffice.ReportQueryController',
        'fastOperate.FastOperationMainController',
        'dailyOffice.ApplyMangerController',
        'resourceManager.BusinessopportunityUploadController',
        'resourceManager.PhotographUploadController'
    ],
    name: 'BqeApp',

    launch: function() {

        Ext.create('BqeApp.view.main.BqeAssistantMainPanel', {fullscreen: true});
    }

});
