/*
 * File: app/store/functionListStore/CommercialManagementStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BqeApp.store.functionListStore.CommercialManagementStore', {
    extend: 'Ext.data.Store',

    requires: [
        'BqeApp.model.FunctionListModel'
    ],

    config: {
        data: [
            {
                functionId: 'salesReport',
                xtype: '',
                iconPath: 'resources/img/icon_sales_report.svg',
                title: '销售报表',
                moreIcon: false
            },
            {
                functionId: 'customerManage',
                xtype: 'customermanagelist',
                iconPath: 'resources/img/icon_customer_namage.svg',
                title: '客户管理',
                moreIcon: false
            },
            {
                functionId: 'ordersQuery',
                xtype: '',
                iconPath: 'resources/img/icon_orders_query.svg',
                title: '订单查询',
                moreIcon: false
            },
            {
                functionId: 'productQuery',
                xtype: '',
                iconPath: 'resources/img/icon_product_query.svg',
                title: '产品查询',
                moreIcon: false
            },
            {
                functionId: 'priceManageMian',
                xtype: 'pricemanagemian',
                iconPath: 'resources/img/icon_price_manage.svg',
                title: '价格管理',
                moreIcon: true
            }
        ],
        model: 'BqeApp.model.FunctionListModel',
        storeId: 'commercialManagementStore'
    }
});