/*
 * File: app/store/functionListStore/DailyOfficeStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    日常办公列表数据
*/
Ext.define('BqeApp.store.functionListStore.DailyOfficeStore', {
    extend: 'Ext.data.Store',

    requires: [
        'BqeApp.model.FunctionListModel'
    ],

    config: {
        data: [
            {
                functionId: 'announcement',
                xtype: 'announcementquery',
                iconPath: 'resources/img/icon_announcement.svg',
                title: '通知公告',
                moreIcon: false
            },
            {
                functionId: 'attendanceManage',
                xtype: 'attendancemanage',
                iconPath: 'resources/img/icon_attendant_manage.svg',
                title: '考勤管理',
                moreIcon: true
            },
            {
                functionId: 'addressBook',
                xtype: '',
                iconPath: 'resources/img/icon_address_book.svg',
                title: '通讯录',
                moreIcon: false
            },
            {
                functionId: 'applyManage',
                xtype: 'applymanagemain',
                iconPath: 'resources/img/icon_apply_manage.svg',
                title: '申请管理',
                moreIcon: true
            },
            {
                functionId: 'reportQuery',
                xtype: 'workreport',
                iconPath: 'resources/img/icon_query_report.svg',
                title: '上报查询',
                moreIcon: false
            },
            {
                functionId: 'workReport',
                xtype: 'workreport',
                iconPath: 'resources/img/icon_workreport.svg',
                title: '工作上报',
                moreIcon: false
            }
        ],
        model: 'BqeApp.model.FunctionListModel',
        storeId: 'dailyOfficeStore'
    }
});