/*
 * File: app/store/functionListStore/SystemSettingsStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BqeApp.store.functionListStore.SystemSettingsStore', {
    extend: 'Ext.data.Store',

    requires: [
        'BqeApp.model.FunctionListModel'
    ],

    config: {
        data: [
            {
                id: '',
                xtype: '',
                title: '拍照设置',
                moreIcon: true
            },
            {
                id: '',
                xtype: '',
                title: '工作日志',
                moreIcon: true
            },
            {
                id: '',
                xtype: '',
                title: '清除数据',
                moreIcon: true
            }
        ],
        model: 'BqeApp.model.FunctionListModel',
        storeId: 'functionListStore.SystemSettingsStore'
    }
});