/*
 * File: app/view/fastOperate/FastOperationSetting.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BqeApp.view.fastOperate.FastOperationSetting', {
    extend: 'Ext.Container',
    alias: 'widget.fastoperationsetting',

    requires: [
        'Ext.field.Toggle'
    ],

    config: {
        fullscreen: true,
        id: 'fastOperationSetting',
        scrollable: true,
        items: [
            {
                xtype: 'togglefield',
                type: 'dailyOffice',
                itemId: 'addressBook',
                label: '<img src="resources/img/icon_address_book.svg"/> <span class="fastOperateSettingTitle">通讯录 </span>',
                labelCls: 'fastOperateSettingCls',
                labelWidth: '68%'
            },
            {
                xtype: 'togglefield',
                type: 'dailyOffice',
                itemId: 'announcement',
                label: '<img src="resources/img/icon_announcement.svg"/><span class="fastOperateSettingTitle">通知公告</span>',
                labelCls: 'fastOperateSettingCls',
                labelWidth: '68%'
            },
            {
                xtype: 'togglefield',
                type: 'dailyOffice',
                itemId: 'workReport',
                label: '<img src="resources/img/icon_workreport.svg"/> <span class="fastOperateSettingTitle">工作上报</span>',
                labelCls: 'fastOperateSettingCls',
                labelWidth: '68%'
            },
            {
                xtype: 'togglefield',
                type: 'dailyOffice',
                itemId: 'reportQuery',
                label: '<img src="resources/img/icon_query_report.svg"/> <span class="fastOperateSettingTitle">上报查询</span>',
                labelCls: 'fastOperateSettingCls',
                labelWidth: '68%'
            },
            {
                xtype: 'togglefield',
                type: 'applyManage',
                itemId: 'applicationUpload',
                label: '<img src="resources/img/icon_application_upload.svg"/> <span class="fastOperateSettingTitle">提交申请</span>',
                labelCls: 'fastOperateSettingCls',
                labelWidth: '68%'
            },
            {
                xtype: 'togglefield',
                type: 'applyManage',
                itemId: 'applicationQuery',
                label: '<img src="resources/img/icon_application_query.svg"/> <span class="fastOperateSettingTitle">申请查询</span>',
                labelCls: 'fastOperateSettingCls',
                labelWidth: '68%'
            },
            {
                xtype: 'togglefield',
                type: 'attendanceManage',
                itemId: 'attendantPushcard',
                label: '<img src="resources/img/icon_attendant_pushcard.svg"/> <span class="fastOperateSettingTitle">考勤打卡</span>',
                labelCls: 'fastOperateSettingCls',
                labelWidth: '68%'
            },
            {
                xtype: 'togglefield',
                type: 'attendanceManage',
                itemId: 'attendantQuery',
                label: '<img src="resources/img/icon_attendant_query.svg"/> <span class="fastOperateSettingTitle">考勤查询</span>',
                labelCls: 'fastOperateSettingCls',
                labelWidth: '68%'
            },
            {
                xtype: 'togglefield',
                type: 'commercialManager',
                itemId: 'customerManage',
                label: '<img src="resources/img/icon_customer_namage.svg"/> <span class="fastOperateSettingTitle">客户管理</span>',
                labelCls: 'fastOperateSettingCls',
                labelWidth: '68%'
            },
            {
                xtype: 'togglefield',
                type: 'commercialManager',
                itemId: 'productQuery',
                label: '<img src="resources/img/icon_product_query.svg"/> <span class="fastOperateSettingTitle">产品查询</span>',
                labelCls: 'fastOperateSettingCls',
                labelWidth: '68%'
            },
            {
                xtype: 'togglefield',
                type: 'priceManage',
                itemId: 'quotedPriceApply',
                label: '<img src="resources/img/icon_quoted_price_apply.svg"/> <span class="fastOperateSettingTitle">报价申请</span>',
                labelCls: 'fastOperateSettingCls',
                labelWidth: '68%'
            },
            {
                xtype: 'togglefield',
                type: 'priceManage',
                itemId: 'quotedPriceQuery',
                label: '<img src="resources/img/icon_quoted_price_query.svg"/> <span class="fastOperateSettingTitle">报价查询</span>',
                labelCls: 'fastOperateSettingCls',
                labelWidth: '68%'
            },
            {
                xtype: 'togglefield',
                type: 'commercialManager',
                itemId: 'ordersQuery',
                label: '<img src="resources/img/icon_orders_query.svg"/> <span class="fastOperateSettingTitle">订单查询</span>',
                labelCls: 'fastOperateSettingCls',
                labelWidth: '68%'
            },
            {
                xtype: 'togglefield',
                type: 'commercialManager',
                itemId: 'salesReport',
                label: '<img src="resources/img/icon_sales_report.svg"/> <span class="fastOperateSettingTitle">销售报表</span>',
                labelCls: 'fastOperateSettingCls',
                labelWidth: '68%'
            },
            {
                xtype: 'togglefield',
                type: 'resourceManager',
                itemId: 'photographUpload',
                label: '<img src="resources/img/icon_upload_photograph.svg"/> <span class="fastOperateSettingTitle">拍照上传</span>',
                labelCls: 'fastOperateSettingCls',
                labelWidth: '68%'
            },
            {
                xtype: 'togglefield',
                type: 'resourceManager',
                itemId: 'businessopportunityUpload',
                label: '<img src="resources/img/icon_upload_businessopportunity.svg"/> <span class="fastOperateSettingTitle">商机上报</span>',
                labelCls: 'fastOperateSettingCls',
                labelWidth: '68%'
            },
            {
                xtype: 'togglefield',
                type: 'resourceManager',
                itemId: 'businessopportunityQuery',
                label: '<img src="resources/img/icon_businessopportunity_query.svg"/> <span class="fastOperateSettingTitle">商机查询</span>',
                labelCls: 'fastOperateSettingCls',
                labelWidth: '68%'
            }
        ]
    }

});